import Link from 'next/link';
import { ArrowRight, ShieldCheck, Star, Truck, WalletCards } from 'lucide-react';
import { WebsiteShell } from '../components/website/website-shell';

const categories = [['Home & Living', 'https://images.unsplash.com/photo-1618220179428-22790b461013?w=800&q=80'], ['Fashion', 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80'], ['Beauty & Care', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80']];
const products = [['Organic Cotton Shirt', '৳1,290', 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80'], ['Ceramic Table Set', '৳2,450', 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&q=80'], ['Leather Everyday Bag', '৳3,200', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80'], ['Aroma Candle', '৳680', 'https://images.unsplash.com/photo-1603006905003-be475563bc59?w=600&q=80']];

export default function Home() { return <WebsiteShell>
<section className="home-hero"><div className="home-hero-copy"><span className="home-kicker">SHOP WITH CONFIDENCE</span><h1>Better products.<br/><em>Better everyday.</em></h1><p>Discover thoughtfully selected products and a shopping experience built around you.</p><div className="home-hero-actions"><Link href="/products" className="primary-cta">Explore products <ArrowRight size={17}/></Link><Link href="/about" className="text-cta">Why NH Mart <ArrowRight size={15}/></Link></div></div><div className="home-hero-art"><div className="art-card art-one"><span>NEW</span><strong>Everyday<br/>essentials</strong></div><div className="art-card art-two"><strong>Made for<br/>your home</strong></div><div className="art-sun"/></div></section>
<section className="trust-strip"><div><Truck size={21}/><span><b>Fast delivery</b><small>Across Bangladesh</small></span></div><div><ShieldCheck size={21}/><span><b>Trusted quality</b><small>Curated products</small></span></div><div><WalletCards size={21}/><span><b>Secure payments</b><small>Shop with confidence</small></span></div></section>
<section className="home-section"><div className="section-heading"><div><span className="home-kicker">EXPLORE THE COLLECTION</span><h2>Shop by category</h2></div><Link href="/products" className="text-cta">View all <ArrowRight size={15}/></Link></div><div className="category-grid">{categories.map(([name,image])=><Link href="/products" className="category-card" key={name}><img src={image} alt=""/><span>{name}</span><ArrowRight size={16}/></Link>)}</div></section>
<section className="home-section featured"><div className="section-heading"><div><span className="home-kicker">CURATED FOR YOU</span><h2>Featured products</h2></div><Link href="/products" className="text-cta">Shop all <ArrowRight size={15}/></Link></div><div className="product-grid">{products.map(([name,price,image])=><Link href="/products" className="product-card" key={name}><div className="product-image"><img src={image} alt={name}/><span>BESTSELLER</span></div><div className="product-meta"><h3>{name}</h3><div className="rating"><Star size={13} fill="currentColor"/> 4.9 <b>{price}</b></div></div></Link>)}</div></section>
<section className="home-banner"><div><span className="home-kicker">THE NH MART PROMISE</span><h2>Good design should<br/>feel this easy.</h2><p>Simple choices, honest prices, and products that earn their place in your everyday.</p><Link href="/about" className="primary-cta">Our story <ArrowRight size={17}/></Link></div></section>
</WebsiteShell>; }
