'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, Eye, EyeOff, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { api } from '../../lib/api';
import { useAuthStore } from '../../stores/auth-store';

export default function Login() {
  const router = useRouter(); const setSession = useAuthStore((state) => state.setSession);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError('Incorrect email or password. Please try again.'); setLoading(true); try { const { data } = await api.post('/auth/login', { email, password }); setSession(data.data.user, data.data.accessToken); router.replace('/admin'); } catch { setError('Incorrect email or password. Please try again.'); } finally { setLoading(false); } }
  return <main className="login-page"><section className="login-showcase"><div className="login-brand"><span>NH</span><b>Mart</b></div><div className="showcase-copy"><span className="showcase-kicker"><Sparkles size={14}/> ADMIN WORKSPACE</span><h1>Manage your<br/><em>business better.</em></h1><p>Everything you need to run NH Mart, thoughtfully organized in one powerful workspace.</p></div><div className="showcase-foot"><ShieldCheck size={16}/> Secure access for authorized administrators only</div></section><section className="login-panel"><div className="login-card"><div className="login-card-icon"><LockKeyhole size={21}/></div><span className="login-eyebrow">WELCOME BACK</span><h2>Sign in to NH Mart</h2><p className="login-subtitle">Enter your credentials to access the admin dashboard.</p>{error&&<div className="login-error">{error}</div>}<form onSubmit={submit}><label>Email address<input type="email" placeholder="admin@example.com" value={email} onChange={(event)=>setEmail(event.target.value)} required autoComplete="email"/></label><label>Password<div className="password-field"><input type={showPassword?'text':'password'} placeholder="Enter your password" value={password} onChange={(event)=>setPassword(event.target.value)} required minLength={8} autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label="Toggle password visibility">{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><button className="login-submit" disabled={loading}>{loading?'Signing in...':'Sign in to dashboard'}<ArrowRight size={17}/></button></form><div className="login-note"><ShieldCheck size={15}/> Your session is protected with secure authentication.</div></div><p className="login-copyright">© {new Date().getFullYear()} NH Mart · Admin portal</p></section></main>;
}

